## Building Predictive Models

In [1]:
import pandas as pd
import os
import numpy as np

In [11]:
processed_data_path = os.path.join(os.path.pardir,'data','processed')
train_file_path = os.path.join(processed_data_path,'train.csv')
test_file_path = os.path.join(processed_data_path,'test.csv')

In [12]:
train_df = pd.read_csv(train_file_path, index_col='PassengerId')
test_df = pd.read_csv(test_file_path, index_col='PassengerId')

In [13]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 1 to 891
Data columns (total 33 columns):
Survived              891 non-null int64
Age                   891 non-null float64
Fare                  891 non-null float64
FamilySize            891 non-null int64
IsMother              891 non-null int64
IsMale                891 non-null int64
Deck_A                891 non-null int64
Deck_B                891 non-null int64
Deck_C                891 non-null int64
Deck_D                891 non-null int64
Deck_E                891 non-null int64
Deck_F                891 non-null int64
Deck_G                891 non-null int64
Deck_Z                891 non-null int64
Pclass_1              891 non-null int64
Pclass_2              891 non-null int64
Pclass_3              891 non-null int64
Title_Lady            891 non-null int64
Title_Master          891 non-null int64
Title_Miss            891 non-null int64
Title_Mr              891 non-null int64
Title_Mrs             891 non-

In [14]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 418 entries, 892 to 1309
Data columns (total 32 columns):
Age                   418 non-null float64
Fare                  418 non-null float64
FamilySize            418 non-null int64
IsMother              418 non-null int64
IsMale                418 non-null int64
Deck_A                418 non-null int64
Deck_B                418 non-null int64
Deck_C                418 non-null int64
Deck_D                418 non-null int64
Deck_E                418 non-null int64
Deck_F                418 non-null int64
Deck_G                418 non-null int64
Deck_Z                418 non-null int64
Pclass_1              418 non-null int64
Pclass_2              418 non-null int64
Pclass_3              418 non-null int64
Title_Lady            418 non-null int64
Title_Master          418 non-null int64
Title_Miss            418 non-null int64
Title_Mr              418 non-null int64
Title_Mrs             418 non-null int64
Title_Officer         418 n

In [15]:
X = train_df.loc[:,'Age':].as_matrix().astype('float')
Y = train_df['Survived'].ravel()

In [17]:
X.shape, Y.shape

((891, 32), (891,))

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)
print(X_train.shape, Y_train.shape)
print(X_test.shape, Y_test.shape)

(712, 32) (712,)
(179, 32) (179,)


In [24]:
print('mean survival in train: {0:.3f}'.format(np.mean(Y_train)))
print('mean survival in train: {0:.3f}'.format(np.mean(Y_test)))

mean survival in train: 0.383
mean survival in train: 0.385


### Check Scikit-Learn Version

In [25]:
import sklearn

In [26]:
sklearn.__version__

'0.23.2'

### Baseline Model

In [27]:
from sklearn.dummy import DummyClassifier

In [28]:
model_dummy = DummyClassifier(strategy='most_frequent', random_state=0)

In [29]:
model_dummy.fit(X_train, Y_train)

DummyClassifier(random_state=0, strategy='most_frequent')

In [30]:
print('Score for Basline Model: {0:.2f}'.format(model_dummy.score(X_test,Y_test)))

Score for Basline Model: 0.61


In [31]:
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score

In [33]:
print('accuracy for baseline model: {0:.2f}'.format(accuracy_score(Y_test,model_dummy.predict(X_test))))

accuracy for baseline model: 0.61


In [34]:
print('confusion matrix for basline model: \n {0}'.format(confusion_matrix(Y_test,model_dummy.predict(X_test))))

confusion matrix for basline model: 
 [[110   0]
 [ 69   0]]


In [35]:
print('precision for baseline model: {0:.2f}'.format(precision_score(Y_test,model_dummy.predict(X_test))))
print('recall for baseline model: {0:.2f}'.format(recall_score(Y_test,model_dummy.predict(X_test))))

precision for baseline model: 0.00
recall for baseline model: 0.00


### First Kaggle Submission

In [36]:
test_X = test_df.as_matrix().astype('float')

In [37]:
predictions = model_dummy.predict(test_X)

In [38]:
df_submission = pd.DataFrame({'PassengerId': test_df.index, 'Survived': predictions})

In [39]:
df_submission.head()

PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         0

In [40]:
submission_data_path = os.path.join(os.path.pardir, 'data', 'external')
submission_file_path = os.path.join(submission_data_path, '01_dummy.csv')

In [41]:
df_submission.to_csv(submission_file_path,index=False)

In [55]:
def get_submission_file(model, filename):
    test_X = test_df.as_matrix().astype('float')
    predictions = model.predict(test_X)
    df_submission = pd.DataFrame({'PassengerId': test_df.index, 'Survived': predictions})
    submission_data_path = os.path.join(os.path.pardir, 'data', 'external')
    submission_file_path = os.path.join(submission_data_path, filename)
    df_submission.to_csv(submission_file_path,index=False)

In [56]:
get_submission_file(model_dummy, '01_dummy.csv')

In [46]:
model_lr_1 = LogisticRegression(random_state=0)

In [47]:
model_lr_1.fit(X_train, Y_train)

LogisticRegression(random_state=0)

In [48]:
print('Score for logistic regression - version 1 : {0:.2f}'.format(model_lr_1.score(X_test, Y_test)))

Score for logistic regression - version 1 : 0.83


In [49]:
print('accuracy for baseline model: {0:.2f}'.format(accuracy_score(Y_test,model_lr_1.predict(X_test))))
print('confusion matrix for basline model: \n {0}'.format(confusion_matrix(Y_test,model_lr_1.predict(X_test))))
print('precision for baseline model: {0:.2f}'.format(precision_score(Y_test,model_lr_1.predict(X_test))))
print('recall for baseline model: {0:.2f}'.format(recall_score(Y_test,model_lr_1.predict(X_test))))

accuracy for baseline model: 0.83
confusion matrix for basline model: 
 [[95 15]
 [15 54]]
precision for baseline model: 0.78
recall for baseline model: 0.78


In [50]:
model_lr_1.coef_

array([[-0.0295758 ,  0.00414504, -0.48810245,  0.55881754, -0.76107834,
         0.12134342, -0.07419859, -0.35967541,  0.47364574,  1.01801601,
         0.2648268 , -0.04876972, -0.36239246,  0.90667036,  0.49166286,
        -0.36553743,  0.10806482,  1.03878911,  0.52130526, -1.49061792,
         1.16450406, -0.10041161, -0.20883793,  0.11929247,  0.22344127,
         0.26963529,  0.42042676,  0.44319075,  0.47306214,  0.1165429 ,
         0.33831588,  0.6944799 ]])

### Second Kaggle Submission

In [57]:
get_submission_file(model_lr_1, '02_lr.csv')

## Part 2

### Hyperparameter Optimization

In [58]:
model_lr = LogisticRegression(random_state=0)

In [59]:
from sklearn.model_selection import GridSearchCV

In [62]:
parameters = {'C':[1.0,10.0,50.0,100.0,1000.0], 'penalty':['l1','l2']}
clf = GridSearchCV(model_lr, param_grid=parameters, cv=3)

In [63]:
clf.fit(X_train, Y_train)

GridSearchCV(cv=3, estimator=LogisticRegression(random_state=0),
             param_grid={'C': [1.0, 10.0, 50.0, 100.0, 1000.0],
                         'penalty': ['l1', 'l2']})

In [64]:
clf.best_params_

{'C': 10.0, 'penalty': 'l2'}

In [65]:
print('best score : {0:.2f}'.format(clf.best_score_))

best score : 0.83


In [66]:
print('Score for logistic regression version 2: {0:.2f}'.format(clf.score(X_test, Y_test)))

Score for logistic regression version 2: 0.84


### making third submission

In [68]:
get_submission_file(clf,'03_lr.csv')

### Feature Normalization and Standardization

### Feature Normalization

In [72]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [73]:
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)

In [75]:
X_train_scaled[:,0].min(), X_train_scaled[:,0].max()

(0.0, 1.0)

In [76]:
X_test_scaled = scaler.transform(X_test)

### Feature Standardization

In [77]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

### Create Model After Standardization

In [78]:
model_lr = LogisticRegression(random_state=0)
parameters = {'C':[1.0,10.0,50.0,100.0,1000.0], 'penalty':['l1','l2']}
clf = GridSearchCV(model_lr, param_grid=parameters, cv=3)
clf.fit(X_train, Y_train)

GridSearchCV(cv=3, estimator=LogisticRegression(random_state=0),
             param_grid={'C': [1.0, 10.0, 50.0, 100.0, 1000.0],
                         'penalty': ['l1', 'l2']})

In [79]:
clf.best_score_

0.8286825278634661

In [80]:
print('Score for logistic regression version 2: {0:.2f}'.format(clf.score(X_test, Y_test)))

Score for logistic regression version 2: 0.84


### Model Persistence

In [81]:
import pickle

In [83]:
model_file_path = os.path.join(os.path.pardir, 'models', 'lr_model.pkl')
scaler_file_path = os.path.join(os.path.pardir, 'models', 'lr_scaler.pkl')

In [85]:
model_file_pickle = open(model_file_path, 'wb')
scaler_file_pickle = open(scaler_file_path, 'wb')

In [86]:
pickle.dump(clf, model_file_pickle)
pickle.dump(scaler, scaler_file_pickle)

In [87]:
model_file_pickle.close()
scaler_file_pickle.close()

#### load persisted files

In [91]:
model_file_pickle = open(model_file_path, 'rb')
scaler_file_pickle = open(scaler_file_path, 'rb')

clf_loaded = pickle.load(model_file_pickle)
scaler_loaded = pickle.load(scaler_file_pickle)

model_file_pickle.close()
scaler_file_pickle.close()

In [92]:
clf_loaded

GridSearchCV(cv=3, estimator=LogisticRegression(random_state=0),
             param_grid={'C': [1.0, 10.0, 50.0, 100.0, 1000.0],
                         'penalty': ['l1', 'l2']})

In [93]:
scaler_loaded

StandardScaler()

In [94]:
X_test_scaled = scaler_loaded.transform(X_test)
print('Score for persisted logistic regression version 2: {0:.2f}'.format(clf_loaded.score(X_test, Y_test)))

Score for persisted logistic regression version 2: 0.84
